### ISSUE TITLE
The lack of `*_imp` classes

### ISSUE THREAD

**Issue by miserva** [pyuvm/pyuvm#106]
I read why pyuvm does not need `*_imp` classes [here](https://github.com/pyuvm/pyuvm/blob/master/pyuvm/s12_uvm_tlm_interfaces.py) and [here](https://dvcon-proceedings.org/wp-content/uploads/Verification-Learns-a-New-Language-%E2%80%93-An-IEEE-1800.2-Implementation.pdf), but I'm not sure I understand the rationale. Let's take a simple put port-imp connection in SystemVerilog for example. `compA` sends a transaction to `compB`.
```systemverilog
class compA extends uvm_component;
  uvm_blocking_put_port #(uvm_sequence_item) dummy_out;
  ...
  // Run phase
    uvm_sequence_item dummy;
    dummy = uvm_sequence_item::type_id::create("dummy", this);
    dummy_out.put(dummy);
```
```systemverilog
class compB extends uvm_component;
  uvm_blocking_put_imp #(uvm_sequence_item, compB) dummy_in;
  ...
  task put(uvm_sequence_item item);
    foo(item);
  endtask

  function void foo(uvm_sequence_item item);
    `uvm_fatal("Test", "Got the dummy")
  endfunction
```
imp allows us to implement `put` in `compB` class, enabling access to `compB`'s members. From what I understand, this is not as straightforward in pyuvm precisely because of the lack of imps. pyuvm seems to expect the user to derive `uvm_*_export` class and implement the TLM method within it. But in this case, to make the `put` call `compB`'s `foo`, the best way is to basically implement a general `blocking_put_imp` class ourselves.
```python
class uvm_blocking_put_imp(uvm_blocking_put_export):
    async def put(self, item):
        try:
            await self.parent.put(item)
        except AttributeError:
            raise UVMTLMConnectionError(f"{self.parent.__class__} must implement put method")
```
Now `compB` can be made just like in SystemVerilog.
```python
class compB(uvm_component):
    def build_phase(self):
        self.dummy_in = uvm_blocking_put_imp("dummy_in", self)
    
    async def put(self, item):
        self.foo(item)
        
    def foo(self, item):
        self.logger.critical("Got the dummy")
        assert False
```
Would it not save effort for the user if `*_imp` classes were included in pyuvm?

**Comment by raysalemi** [comment]
I don't see how the `_imp` adds value to this solution.  

What about 

```python
class compB(uvm_component, uvm_put_export):

  async def put(self, item):
    self.foo(item)

 def foo(self, item):
    self.logger.critical("got the dummy");
    assert False
```

**Comment by miserva** [comment]
Good call, I didn't even consider multiple inheritance. But it leads to "TypeError: Cannot create a consistent method resolution order (MRO) for bases uvm_component, uvm_put_export". I guess it's because uvm_put_export is a derived class of uvm_component. So actually, compB could just be a derived class of uvm_put_export:
```python
class compB(uvm_put_export):
```
Then the put port is connected straight to compB:
```python
self.compA.dummy_out.connect(self.compB)
```
It's a bit confusing solution but it works.
