### ISSUE TITLE
Add TLM methods to uvm_tlm_fifo_base

### ISSUE THREAD

**Issue by miserva** [pyuvm/pyuvm#107]
In SystemVerilog UVM, FIFOs can call TLM methods. For example,
```systemverilog
uvm_tlm_analysis_fifo #(my_seq_item) my_fifo;
...
my_fifo.get(item);
```
In pyuvm, this requires an extra step of attaching a get port and using its get method.
```python
self.my_fifo = uvm_tlm_analysis_fifo("my_fifo", self)
self.my_get_port = uvm_get_port("my_get_port", self)
...
self.my_get_port.connect(self.my_fifo.get_export)
...
item = await self.my_get_port.get()
```

However, `uvm_tlm_fifo_base` could implement the TLM methods as follows:
```python
async def get(self):
    return await self.get_export.get()
```

Then FIFOs would work like in SystemVerilog.
```python
item = await self.my_fifo.get()
```

**Comment by raysalemi** [comment]
It's funny that I would leave this out as the methodology in _FPGA Simulation_ relies upon this functionality.
