### ISSUE TITLE
@pyuvm.test does not work with TESTCASE

### ISSUE THREAD

**Issue by miserva** [pyuvm/pyuvm#109]
Running a specific test case with cocotb's [`TESTCASE`](https://docs.cocotb.org/en/stable/building.html#envvar-TESTCASE) environment variable does not work with `@pyuvm.test()` decorator.
For example, in TinyALU, running `make TESTCASE=AluTest` returns:

```
Traceback (most recent call last):
  File "/.../lib/python3.7/site-packages/cocotb/__init__.py", line 242, in _initialise_testbench
    _initialise_testbench_(argv_)
  File "/.../lib/python3.7/site-packages/cocotb/__init__.py", line 344, in _initialise_testbench_
    regression_manager = RegressionManager.from_discovery(top)
  File "/.../lib/python3.7/site-packages/cocotb/regression.py", line 147, in from_discovery
    return cls(dut, tests)
  File "/.../lib/python3.7/site-packages/cocotb/regression.py", line 126, in __init__
    for test in tests:
  File "/.../lib/python3.7/site-packages/cocotb/regression.py", line 193, in _discover_tests
    raise ImportError("Failed to find requested test %s" % test_name)
ImportError: Failed to find requested test AluTest
...
#      0.00ns ERROR    Requested AluTest from module testbench isn't a cocotb.test decorated coroutine
#      0.00ns ERROR    Failing test at simulator request before test run completion: Simulator shutdown prematurely
```

**Comment by DedkovEA** [comment]
Despite of issue closed and fix merged, I have the same issue on 3.0.0 version. Inspecting master branch shows, that #110 commit is currently missed (or I misunderstood something about how git works).

Temporal workaround for me is replacing the name in 43 line as follows
`setattr(caller_module, f"test_{test._id}", test)` -> `setattr(caller_module, f"pyuvmtest_{cls.__name__}", test)`
This barely breaks anything while allows using convenient test cases names.

**Comment by raysalemi** [comment]
This is not expected to work with **pyuvm**'s @pyuvm.test() decorator

**Comment by raysalemi** [comment]
Hi,

Users can create `TESTNAME=MYTEST` functionality by creating a **cocotb** test that explicitly starts a test using `uvm_root.run_test("MYTEST")`.

Since the functionality exists without being too ugly and decided that we would just leave this alone.
