### ISSUE TITLE
flake8 on tests?

### ISSUE THREAD

**Issue by raysalemi** [pyuvm/pyuvm#11]
@tudortimi, we have flake8 running on the pyuvm directory. Do you think it should run on the tests?

I'm ambivalent, what is the common practice?

**Comment by tudortimi** [comment]
Gotta say, I don't know. Python is more of a hobby also for me.

I'd treat the tests with the same level of rigor when it comes to style.

**Comment by raysalemi** [comment]
Okay. I have fixed the tests to pass flake8, fixed the action to check only the `pyuvm` and `tests/pytests` directory  and fixed the action to fail if flake8 detects errors. 

I just pushed those changes.
