### ISSUE TITLE
Run phase doesn't wait for objections from all components to drop

### ISSUE THREAD

**Issue by mkorbel1** [pyuvm/pyuvm#112]
If there are two (or more) components which raise and drop objections in a test, the first component which reaches zero remaining raised objections will end the run phase, even if other components have not yet dropped all of their objections.

For example, suppose we have two components c1 and c2:
```
c1 raise_objection
c2 raise_objection
c1 drop_objection
<<< run phase erroneously ends here
c2 drop_objection
<<< run phase should end here
```

I believe the bug is in this code in utility_classes.py:
```python
    def raise_objection(self, raiser):
        name = raiser.get_full_name()
        self.__objections[name] = self.__objections.setdefault(name, 0) + 1
        self.objection_raised = True
        self._objection_event.clear()

    def drop_objection(self, dropper):
        name = dropper.get_full_name()
        try:
            self.__objections[name] -= 1
        except KeyError:
            self.objection_raised = True
            pass
        if self.__objections[name] == 0:
            del self.__objections[name]
            self._objection_event.set()
```

Note that the `_objection_event` is set if only `name`'s objections are all dropped, without checking if any other objections in `__objections` are raised.

I think a simple modification like this might suffice:
```python
    def drop_objection(self, dropper):
        name = dropper.get_full_name()
        try:
            self.__objections[name] -= 1
        except KeyError:
            self.objection_raised = True
            pass
        if self.__objections[name] == 0:
            del self.__objections[name]
            
            # only signal all objections done if none exist anywhere
            if len(self.__objections) == 0:
                self._objection_event.set()
```

I think existing tests in pyuvm could be modified in minor ways to cover this.

I discovered the issue in reimplementing some code originally written in ROHD-VF (https://github.com/intel/rohd-vf) to compare functionality and features with pyuvm.

**Comment by raysalemi** [comment]
Good catch!

I've just started work as a High School teacher and so I'm unlikely to be able to fix it until Thanksgiving break.  Would you be open to submitting a pull request with the fix and updated test?

**Comment by mkorbel1** [comment]
Sure, I'll take a shot at submitting a PR in within the next week or so.  Feel free to assign to me
