### ISSUE TITLE
PyUVM + Cocotb + Icarus on Windows - how to get LOG file?

### ISSUE THREAD

**Issue by svenka3** [pyuvm/pyuvm#114]
Setup:
PyUVM + Cocotb + Icarus on Windows + MSYS64

I use the make sim, but no LOG file gets generated, I did a | tee for now. What's the recommended approach to getting a simulation log file?

Thanks
Srini

**Comment by raysalemi** [comment]
> Setup:
> 
> PyUVM + Cocotb + Icarus on Windows + MSYS64
> 
> 
> 
> I use the make sim, but no LOG file gets generated, I did a | tee for now. What's the recommended approach to getting a simulation log file?
> 
> 
> 
> 
> 
> Thanks
> 
> Srini 

Good question. I've never worked with that combination, nor have I ever generated a log file from Icarus (though, I use it on the Mac.)

Maybe check stackoverflow.com?

**Comment by miserva** [comment]
I don't use Icarus myself, but I can try to give general advice. I assume the log creation is simply missing from cocotb's default Icarus simulation flow like I've noticed it missing for another simulator.

To add it, check the Icarus documentation if there is a flag to enable logfile creation. Then add it in your Makefile to `SIM_ARGS` or whatever `*_ARGS` is appropriate. See cocotb documentation for the available Makefile arguments.

Alternatively, you could copy Makefile.sim and Makefile.icarus from the cocotb library to create your own custom flow and, for instance, add `| tee $(SIM_BUILD)/sim.log` to the end of the simulation command.

If this didn't help you, then people at cocotb github surely have experience with cocotb+Icarus.
