### ISSUE TITLE
Test  tests/cocotb_tests/t12_tlm is hanging

### ISSUE THREAD

**Issue by raysalemi** [pyuvm/pyuvm#116]
Hi @ktbarrett ,

There is an odd decorator name `@test` in this test that seems to be hanging in cocotb 1.7.1.  This is what's causing the head of **pyuvm** to hang.

The test hangs with both the modifications to update `@pytest` and in the current `master/HEAD`.

Could you tell me what that decorator is supposed to be doing and how to fix this issue?

Thanks!
Ray

**Comment by raysalemi** [comment]
Very strange.  It hangs when I use `@cocotb.test()`, but only in this test.  `@cocotb.test()` works in `t09`, for example.

**Comment by raysalemi** [comment]
The same test works with `@pyuvm.test()`

**Comment by ktbarrett** [comment]
You are talking about [this](https://github.com/pyuvm/pyuvm/commit/e0eaf783f91fe035de232972fd768433d526287c#diff-2556934c2659fee552abaf47abb875fabc27c1852c8b0bb2135e7a186c1b5b38L97-L100) right?

**Comment by raysalemi** [comment]
@ktbarrett fixed this
