### ISSUE TITLE
Using tox with Python 3.6/3.9 etc.

### ISSUE THREAD

**Issue by svenka3** [pyuvm/pyuvm#122]
File: https://github.com/pyuvm/pyuvm/blob/master/tox.ini

I am novice user of tox so am not aware of all consequences of the below issue/fix/observation. I tried running tox with pyuvm - BTW I couldn't locate instructions to do this (once you know it, it is obvious..type "tox", make sure it is installed etc.). 

In tox.ini file I see we choose py37 or 38 with a commented line supporting other versions.
 
```tox
envlist = py{35,36,37,38,39}-{linux,macos,windows},docs
```
I tried it on Linux CentOS with Python 3.6.8 and below line seems to work (ghdl didn't work yet, but not my focus right now). Also "docs" showed a failure, so removed that. Below is modified tox.ini line:
```tox
# Srini envlist = py{37, 38}-{linux,macos,windows}
envlist = py{35,36,37,38,39}-{linux,macos,windows}
```
Any inputs on if this is a OK change? Do you need a PR?

Thanks

**Comment by raysalemi** [comment]
A PR would be great!

**Comment by raysalemi** [comment]
Thanks for the PR!

> File: https://github.com/pyuvm/pyuvm/blob/master/tox.ini
> 
> 
> 
> I am novice user of tox so am not aware of all consequences of the below issue/fix/observation. I tried running tox with pyuvm - BTW I couldn't locate instructions to do this (once you know it, it is obvious..type "tox", make sure it is installed etc.). 
> 
> 
> 
> In tox.ini file I see we choose py37 or 38 with a commented line supporting other versions.
> 
>  
> 
> ```tox
> 
> envlist = py{35,36,37,38,39}-{linux,macos,windows},docs
> 
> ```
> 
> I tried it on Linux CentOS with Python 3.6.8 and below line seems to work (ghdl didn't work yet, but not my focus right now). Also "docs" showed a failure, so removed that. Below is modified tox.ini line:
> 
> ```tox
> 
> # Srini envlist = py{37, 38}-{linux,macos,windows}
> 
> envlist = py{35,36,37,38,39}-{linux,macos,windows}
> 
> ```
> 
> Any inputs on if this is a OK change? Do you need a PR?
> 
> 
> 
> Thanks
> 
> 
> 
>
