### ISSUE TITLE
@pyuvm.test() - NameError: name 'pyuvm' is not defined

### ISSUE THREAD

**Issue by nawaznedian** [pyuvm/pyuvm#138]
Hi Ray,

Hope you're doing well. I was testing the following example illustrated in your book and the pyuvm decorator seems to cause an issue but I am able to print the type and object name. Thoughts? @raysalemi 

Code:
from pyuvm import *

my_object = uvm_object("my_first_object")
print(type(my_object))
print("object name:", my_object.get_name())

@pyuvm.test()
class HelloWorldTest(uvm_test):
    async def run_phase(self):
        self.raise_objection()
        self.logger.info("Hello, World!!")
        self.drop_objection()

Output:
<class 'pyuvm.s05_base_classes.uvm_object'>
object name: my_first_object
Traceback (most recent call last):
  File "pyuvm_test_001.py", line 7, in <module>
    @pyuvm.test()
NameError: name 'pyuvm' is not defined

**Comment by nawaznedian** [comment]
Rectified this error by adding the following
import pyuvm

Still not able to see any output "Hello, World!!"

**Comment by raysalemi** [comment]
Are the indents correct?

**Comment by nawaznedian** [comment]
Yes they are
![image](https://user-images.githubusercontent.com/128752668/227393147-5f6dd41e-c862-4111-a176-03ca0b565695.png)

**Comment by raysalemi** [comment]
Why is pyuvm underlined?

I think you may have a path problem. Is pyuvm really being found?

**Comment by raysalemi** [comment]
It works for me. What simulator are you using?  Could you share the output?

**Comment by nawaznedian** [comment]
I got it working, need some adjustment in Makefile and running fine. Thank you
