### ISSUE TITLE
Implementation of runtime phases

### ISSUE THREAD

**Issue by timothyscherer** [pyuvm/pyuvm#179]
Was there any particular reason not to implement the runtime phases? This seems useful and also (as far as I can tell) seems to be part of UVM, and not unique to the SV implementation. It should be very easy to add this, and I would be happy to do it if it is desirable.

![image](https://github.com/pyuvm/pyuvm/assets/68401889/b3889837-8b4d-4204-9451-7481227858fa)

**Comment by raysalemi** [comment]
The whole modifiable phase system is generally deemed to be a failure.  

Have you ever seen the runtime phases used?

**Comment by timothyscherer** [comment]
This is my first real dive into UVM, so I'm learning as I go (using pyuvm). I basically just ran into the problem of implementing resets in my design and after some research I found a few places that referenced this phasing scheme.

It seems useful to me, but there isn't any particular reason I can't just bunch it all up in the run_phase. I was just curious if it would be better practice to follow these phases.

It also wouldn't hurt to implement (I think), since it would be backwards compatible anyway. What are your thoughts?

**Comment by raysalemi** [comment]
I agree with myself. 🙂

Nobody uses those phases.

**Comment by damnsavage** [comment]
I think the concept is good but the implementation in SV was too costly in terms of code, hard to use and had too many phases. I use a simplified approach, which I think is common, define virtual tasks in your base test e.g. reset, configure, main, shutdown. The run_phase() of your base test calls them: reset(); configure(); main(); shutdown();

Most tests use the same reset, configure and shutdown phases which are defined once in the base test. 
Each testcase only contains the main task and maybe some constraints on the configDB object.

If you need a new check at the the end of all tests update the shutdown task.
If some additional configuration is required update configure task etc...

So the advantages are shared code in test base. Easy to add something to all tests.
The same can be done in pyuvm without any additional infrastructure.
