### ISSUE TITLE
Passing arrays from Monitor to Scoreboard

### ISSUE THREAD

**Issue by davidp135** [pyuvm/pyuvm#180]
Hi, 

I am writing my own pyuvm testbench and have come into some issues when capturing some output data into an array in a Monitor and passing it to my Scoreboard via `uvm_tlm_analysis_fifo`.

The testbench structure is the same as in your example. Here is the sequence of events: 
1. The outputs from a DUT are captured into a numpy array in my monitor and put into the monitor queue using `put_nowait`.
2. The monitor `get` command in the pulls the array out of the queue.
3. The array is pulled correctly in the Monitor `datum = await self.get_method()`
4. During the Scoreboard `check_phase` the array outputs are pulled as required.

My issue is that during the Scoreboard check_phase the last item put into the uvm_tlm_analysis_fifo is read every-time. So if there are 4 test results to check. There will be 4 successful `try_get`s, but the result that is output will always be the same value.

I have hacked your example testbench to illustrate my issue. The driver side on the testbench is unchanged, but `cmd_mon_bfm` outputs dummy array data rather than actual dut outputs. I have attached the testbench as a zip to this issue if that is ok.

As can be seen from the logger outputs the array gets pushed in and out queue logic successfully until the boundary between Monitor (`self.logger.info(f"MONITORED {datum}")`) and Scoreboard (`self.logger.info(f"check_phase array: {cmd}")`)

If a single non-array value is sent from the `cmd_mon_bfm` all the way to the scoreboard check_phase. The fifo logic works correctly. I have also tried the standard python array logic and that seems to have the same issues as the numpy array.

I have looked through the pyuvm source code and can't find why this issue is occurring. Would you be able to help?

Thanks

[pyuvm_array_test.zip](https://github.com/pyuvm/pyuvm/files/12651276/pyuvm_array_test.zip)

**Comment by raysalemi** [comment]
My first thought is that you are using the same handle for your four puts. Maybe you are making one object outside a loop and then populating it and putting it. 

To check, use the id() function after each get to see if you are getting the same object each time.

**Comment by davidp135** [comment]
Hi Ray,
Thank you for getting back to me. I have added print outs of the array ids. The ID is the same the whole way through the testbench. My Python knowledge isn't great, but I think this is what you are looking for?
![image](https://github.com/pyuvm/pyuvm/assets/88392351/25b57531-aa31-477e-ab65-6e1c6fd2f45a)

[pyuvm_array_test.zip](https://github.com/pyuvm/pyuvm/files/12657630/pyuvm_array_test.zip)

**Comment by raysalemi** [comment]
Yes. You are putting the same object into the FIFO over and over.

You need to create a new object when you receive a new transaction.

**Comment by davidp135** [comment]
Great thank you Ray. That has fixed my issue.
