### ISSUE TITLE
uvm_driver uses uvm_sequence_item_port instead of uvm_seq_item_pull_port

### ISSUE THREAD

**Issue by timothyscherer** [pyuvm/pyuvm#184]
I am attempting to implement a driver which needs to [process items in parallel](https://learnuvmverification.com/index.php/2015/10/28/uvm-driver-use-models-part-2/). It is my understanding that this cannot be accomplished using `get_next_item()` and `item_done()`, but the `get()` and `put()` methods are not included in `uvm_driver.seq_item_port` since it has the wrong type.

```sv
class uvm_driver #(type REQ=uvm_sequence_item,
                   type RSP=REQ) extends uvm_component;


  // Port: seq_item_port
  //
  // Derived driver classes should use this port to request items from the
  // sequencer. They may also use it to send responses back.

  uvm_seq_item_pull_port #(REQ, RSP) seq_item_port;

  uvm_seq_item_pull_port #(REQ, RSP) seq_item_prod_if; // alias

  // Port: rsp_port
  //
  // This port provides an alternate way of sending responses back to the
  // originating sequencer. Which port to use depends on which export the
  // sequencer provides for connection.

  uvm_analysis_port #(RSP) rsp_port;

  REQ req;
  RSP rsp;

  // Function: new
  //
  // Creates and initializes an instance of this class using the normal
  // constructor arguments for <uvm_component>: ~name~ is the name of the
  // instance, and ~parent~ is the handle to the hierarchical parent, if any.

  function new (string name, uvm_component parent);
    super.new(name, parent);
    seq_item_port    = new("seq_item_port", this);
    rsp_port         = new("rsp_port", this);
    seq_item_prod_if = seq_item_port;
  endfunction // new

  const static string type_name = "uvm_driver #(REQ,RSP)";

  virtual function string get_type_name ();
    return type_name;
  endfunction

endclass
```

```py
class uvm_driver(uvm_component):

    def __init__(self, name, parent):
        super().__init__(name, parent)
        self.seq_item_port = uvm_seq_item_port("seq_item_port", self)
```

**Comment by raysalemi** [comment]
I don't understand the question.

**Comment by timothyscherer** [comment]
The question is whether or not it is possible to process sequence items in parallel. My research indicates that this is possible with UVM, but it seems that I cannot use the same methods in pyuvm.

The `uvm_driver` should have an attribute `seq_item_port` of type `uvm_seq_item_pull_port`. However, in pyuvm, the type is `uvm_seq_item_port`.

The only item accessor in pyuvm is `uvm_seq_item_export.get_next_item()` which requires an item to be done before getting the next one, meaning no parallel processing of items.

**Comment by raysalemi** [comment]
The solution is to call item_done() immediately upon getting an item. 

You then use some other way to handle timing.

**Comment by raysalemi** [comment]
Have you discovered [Verification Acadamy?](http://www.verificationacademy.coml).  There is definitely an article there that discusses this design pattern.

**Comment by raysalemi** [comment]
@timothyscherer , Fixed URL : https://verificationacademy.com

**Comment by raysalemi** [comment]
You can do things with put() and get(). But described the accepted approach for the past 15 years. 

I suggest verificationacademy.com

**Comment by timothyscherer** [comment]
I am using verification academy (https://verificationacademy.com/cookbook/driver/pipelined), and that is where I found the recommendation to use get and put. If you were you immediately call item_done you would have no way of blocking the calling sequence until the transaction is actually done, thus no way for the sequence to know the response data is valid.

Maybe the better question is this: why does pyuvm not implement the uvm_seq_item_pull_port? This is the type that gets created in the driver in the UVM classes.

**Comment by raysalemi** [comment]
I don't think I'd ever seen it. I refactored the driver system as I found the spec indecipherable.  

It's certainly worth investigating.

**Comment by raysalemi** [comment]
I haven't tried it yet, but I think one can connect a `uvm_put_export` to any put_port.  So you could get the `put()` function, for example.

Did you ever solve this?

**Comment by raysalemi** [comment]
It is not  clear to me that this is still an issue.
