### ISSUE TITLE
Reconsidering Python Assertions for Run-Time Checks

### ISSUE THREAD

**Issue by hzisman** [pyuvm/pyuvm#187]
Currently all the run time check in the code are implemented with the `assert` statement. for example: https://github.com/pyuvm/pyuvm/blob/29092b37282d49775949de3af9a25d8615c8b5f8/pyuvm/s05_base_classes.py#L57

Thats raises concerns as they are disabled in non-debug mode.

In my opinion, assertions should only be used for development time checks, while run time errors should be raised with explicit `raise` statement.

I know this makes the code much longer and in some opinions less readable, but I think it's worth discussing.

**Comment by raysalemi** [comment]
Good point. I did not know that. I've always run in the default mode, which is the debug mode.  

I could support such a project, though I don't have time to do it.

**Comment by hzisman** [comment]
No problem, I can work on that.
please assign it to me

**Comment by raysalemi** [comment]
@hzisman I am not sure where we stand on this.
