### ISSUE TITLE
Problems with scoreboard

### ISSUE THREAD

**Issue by hurisson** [pyuvm/pyuvm#188]
Hello!
 I ran into a problem - when I try to output fifo contents in run_phase, I get nothing. (this works in SV) However, I can get the data in check_phase. Can you tell me how I can parse the data in run_phase?
![image](https://github.com/pyuvm/pyuvm/assets/61613953/ba839031-3610-4ec6-afd6-1d789e92c8b8)

I also found in the source code in the class uvm_GetPeekExport the initialization nonblocking_get_export, it seems to me that the port there should be get_ap, instead of put_ap..
![image](https://github.com/pyuvm/pyuvm/assets/61613953/4f35424b-6748-4d13-86d4-0252470282a6)

**Comment by hurisson** [comment]
Thank you very much, Ray! Indeed, I forgot about waiting - await . Now I can compare received transactions in run_phase
```
    async def run_phase (self):
        c1 = cocotb.start_soon(self.get_apb_slv_trn())
        c2 = cocotb.start_soon(self.get_lpi_trn())
        c3 = cocotb.start_soon(self.get_rst_dut_trn())
        cocotb.triggers.Combine(c1, c2, c3)
        while True:
            self.apb_mst_trn = await self.mst_fifo_trans.get()
            await cocotb.triggers.Timer(1.0, "ns") #nba-region
            if (self.apb_mst_trn.curr_state != apb_state.ABORTED.name):
                await self.check_trn(self.apb_mst_trn, self.apb_slv_trn)
```

I also wanted to ask, does the port driver not support non-blocking assignment in the form seq_item_port.try_next_item? 

And is it possible to somehow implement many write_* functions in uvm_subcriber, just like in SV by declaring the uvm macro `uvm_analysis_imp_decl(_cov_slv) for each port? 

```
For example:
`uvm_analysis_imp_decl(_slv_cov)
`uvm_analysis_imp_decl(_mst_cov)

class cov_collector()
  function void cov_collector::write_slv_cov(slv_transaction t);
    state_slv.sample(t.xact_type)
  endfunction: write_slv_cov
  
  function void cov_collector::write_mst_cov(mst_transaction t);
    state_mst.sample(t.xact_type)
  endfunction: write_mst_cov
```

**Comment by hurisson** [comment]
UPD: I managed to do it successfully
![image](https://github.com/pyuvm/pyuvm/assets/61613953/28612a64-7400-425c-8c1d-5c7c3a43c296)

**Comment by raysalemi** [comment]
That's a cool way to solve the problem of multiple write functions!

**Comment by raysalemi** [comment]
Conversation completed
