### ISSUE TITLE
Conflicting types uvm_access_e and access_e in RAL implementation

### ISSUE THREAD

**Issue by KasperHesse** [pyuvm/pyuvm#189]
Hello
I am looking at the RAL implementation being developed on the `ral_dev` branch and have come across the following which I believe to be an error:

In `s17_uvm_req_enumerations`, the type `uvm_access_e` is defined (and properly referenced as originating from section 17.2.2.6 in 1800.2 spec)

https://github.com/pyuvm/pyuvm/blob/04220554378af4ec5d0fac6003945bbbae94aa1d/pyuvm/s17_uvm_reg_enumerations.py#L108-L111

In `s24_uvm_reg_includes`, the type `access_e` is defined. I have been unable to find this definition anywhere in the IEEE 1800.2 spec.
https://github.com/pyuvm/pyuvm/blob/04220554378af4ec5d0fac6003945bbbae94aa1d/pyuvm/s24_uvm_reg_includes.py#L55-L63

Generally speaking, there are a lot of multiple definitions in `s24_reg_includes` that are identical to the definitions from `s17_uvm_reg_enumeration`, but without the `uvm` prefix. 

The definitions from `s24_uvm_reg_includes` are being used throughout the codebase in favour of the definitions from `s17_uvm_reg_enumerations`. Is this on purpose or an oversight? I would expect the RAL to use the known names and types in methods to ease the transition from SV to Python. 
See e.g. `uvm_reg_bus_op`, defined in `s24_uvm_reg_includes`, which should have `kind: uvm_access_e` but the field is defined as `kind: access_e`)

**Comment by raysalemi** [comment]
Could you mention this issue on the RAL_Development discussion?  That would notify the folks working on that branch.

**Comment by raysalemi** [comment]
Moved to ral_development
