### ISSUE TITLE
Update tests to fail if cocotb test has FAIL in the log

### ISSUE THREAD

**Issue by raysalemi** [pyuvm/pyuvm#19]
Today all tests using `@cocotb.test()` pass regardless of whether they say they fail.  

**pyuvm** needs a mechanism to see the `FAIL`  messages and fail.

**Comment by themperek** [comment]
Most of the time the way this is done is by checking `results.xml` file.
I cocotb:
https://github.com/cocotb/cocotb/blob/master/bin/combine_results.py

In [cocotb-test](https://github.com/themperek/cocotb-test):
https://github.com/themperek/cocotb-test/blob/19b1cd087407926005ac8c865934455e913b8b76/cocotb_test/simulator.py#L219-L228

**Comment by raysalemi** [comment]
Thanks. I swiped the combine_results.py script and am using it now.
