### ISSUE TITLE
Any insights on PyUVM vs UVM-Python

### ISSUE THREAD

**Issue by sbhutada** [pyuvm/pyuvm#191]
I would like to decide which Python UVM library to proceed with. 

Is there a support for RAL in PyUVM? When might it be ready?

Any examples with PyVSC? Or should we use cocotb-coverage?

Thanks.

**Comment by raysalemi** [comment]
Hi,

The libraries you mention are all orthogonal:

* **pyuvm** provides the reuse and structure available in UVM
* The `ral_dev` branch on **pyuvm** contains the current state of RAL development. It's nearly complete if you'd like to try it. 
* **PyVSC** can be used with **pyuvm**.  The randomization can go into sequences and the coverage can go into coverage components.
* You can use **cocotb-coverage** in coverage components as well.

Ray

**Comment by mballance** [comment]
Hi @raysalemi,
    Are you open to having contributed examples that use external libraries included with PyUVM? I think it should be possible to setup the Makefile to check for required packages, and error out if any are missing.

-Matthew

**Comment by raysalemi** [comment]
Hi Matt,

I am open to it, don't have time to contribute.  I'm still putting all my cycles into making high school curriculum. 

Ray

**Comment by mballance** [comment]
Hi Ray,
    Thanks for confirming that you'd be open to including contributed examples in the PyUVM repo. Not sure I'll have time in the short-term to develop anything either, but good to have a tentative plan around where such examples can go.

-Matthew

**Comment by raysalemi** [comment]
I think it would be cool to have a pyuvm/pyVSC path for users.

I plan to get the dev release of RAL out during February vacation.

**Comment by raysalemi** [comment]
We completed this conversation.
