### ISSUE TITLE
pyuvm + latest cocotb: Decorator and LogicArray

### ISSUE THREAD

**Issue by LeoGoTi** [pyuvm/pyuvm#192]
I'm recently working to adapt to pyuvm for FPGA verification, and some attempts with latest cocotb version shows there are some compatability issues running `TinyAlu Test`. The environment informations are as follows:
- OS: `centos 7`
- `python`: 3.6.8
- `cocotb`: 2.0.0.dev0
- `pyuvm`: 2.9.1

The issues come from two code snippets:
First, in `extension_classes.py`:
```python
# adds cocotb.test object to caller's module
caller_frame = inspect.stack()[1]
caller_module = inspect.getmodule(caller_frame[0])
setattr(caller_module, f"test_{test._id}", test)
```
It generally works with `cocotb-1.8.1`, while since `2.0.0`(still under development), `_id` attribute is no longer retrievable from `test`. Inside `cocotb`, the test is registered using `cocotb.regression_manager.register_test()`, and the test is later put into `cocotb.regression_manager._queue` (a list).
So my workaround is to substitude the last line of `setattr` by:
```python
rm = cocotb.regression_manager
_test = rm._queue[len(rm._queue) - 1]
setattr(caller_module, f"test_{_test._id}", test) # ._id is no longer retrievable since cocotb 2.0.0
```

It's not quite elegant, but it works.

The workaround takes the test to the second issue, in `tinyalu_utils.py`:
```python
def get_int(signal):
    try:
        sig = int(signal.value)
    except ValueError:
        sig = 0
    return sig
```

When casting `signal.value` to `int`, a `TypeError` is raised since `signal.value` is a `LogicArray`. The workaround is as follows:
```python
# import LogicArray symbol
from cocotb.types.logic_array import LogicArray
...

def get_int(signal):
    try:
        if isinstance(signal, LogicArray):
            sig = signal.integer
        else:
            sig = int(signal.value)
            
    except ValueError:
        sig = 0
    return sig
```

(Actually there is a third issue, about `cocotb.fork`, which is fixed by previous patches.)

I believe that the **Second** fix should apply to both versions of `cocotb`, while the **First** is still subject to changes from further development.
However, from [the latest release notes of cocotb](https://docs.cocotb.org/en/latest/release_notes.html), `RegressionManager` uses a new mechanism to discover tests, making `._id` something inside `RM` and invisible. (See [#3578](https://github.com/cocotb/cocotb/pull/3578))

Are the changes above necessary for current `pyuvm`?

**Comment by leehongming** [comment]
Good job

**Comment by raysalemi** [comment]
The second issue is an easy fix since it is not part of **pyuvm** proper.  It is part of an example.

However, I think this issue should be raised on **cocotb** issues so that they are aware that they are introducing an incompatibility with existing testbenchs.  

Similarly, the first issue should be raised with **cocotb** so they are aware of incompatibilities with existing code.   

@ktbarrett, what are your thoughts on these issues?

**Comment by ktbarrett** [comment]
We are going for a 2.0 (major rev), there will be incompatibilities. I would not bother trying to change anything just yet, there are still changes being made. For sure the second issue will be fixed, the first will require changes in this repo.

**Comment by raysalemi** [comment]
@LeoGoTi , has this issue changed since you reported it?

**Comment by LeoGoTi** [comment]
Hi, @raysalemi , sorry for leaving this issue behind.

I have been working with `pyuvm-2.9.1` + `cocotb-1.8.1` since then, instead of with `cocotb-2.0.0.dev`.

### For the first issue (about test id)
Unfortunately in the latest `cocotb` dev version, `._id` seems gone.

As far as I have learned, `test_{_test._id}` can be replaced by an f-string whose index value comes from a `pyvum`-internal integer. This string is not directly visible, at least when you run tests with `@pyuvm.test()`. 

Although sometimes I would enter `make TESTCASE=test_0` to run a specific test decorated by `@pyuvm.test()`, It won't bother if the `test_0` changes to anything else.

### For the second issue (about LogicArray2integer)
I have read more code inside `cocotb`, as well as the reference card [here](https://docs.cocotb.org/en/stable/refcard.html). `signal.value.interger` is the currently preferred syntax for me when trying to get an integer value of a signal. Besides, I believe assigning `COCOTB_RESOLVE_X=ZEROS` can help to simplify the snippet from -
```python
def get_int(signal):
    try:
        sig = int(signal.value)
    except ValueError:
        sig = 0
    return sig
```
to - 
```python
def get_int(signal):
    return signal.value.integer
```

Hope these help.

**Comment by raysalemi** [comment]
Hi @LeoGoTi ,

Thanks for the update.

BTW. I tried that change on my installation, and it hung the simulation.
I wonder if we are at different versions of cocotb.

Ray

**Comment by raysalemi** [comment]
I am thinking I should lock pyuvm to the current 1.7 release for now until I can test with 1.8+

Maybe the test_id goes into the decorator?

**Comment by raysalemi** [comment]
I see what you're saying...

**Comment by raysalemi** [comment]
Now the `signal.value.integer` method works.

**Comment by ktbarrett** [comment]
The `test_id` stuff is no longer necessary as of the latest version of cocotb. [These lines](https://github.com/pyuvm/pyuvm/blob/9925dfec96990cc26bbe357ac1f172527e942600/pyuvm/extension_classes.py#L47-L50) can be version ifdef'd out in 2.0.

**Comment by raysalemi** [comment]
We've now locked pyuvm to < 2.0.
