### ISSUE TITLE
Any example that mimics uvm_component_param_utils?

### ISSUE THREAD

**Issue by sbhutada** [pyuvm/pyuvm#193]
Is there an example that shows parameteized UVM components and objects? Thanks.

**Comment by raysalemi** [comment]
Hi Shashi,

If by "parameterized" you mean a way of passing types to an object, there is no need for that in **pyuvm**.  It is untyped.

**Comment by sbhutada** [comment]
Hi Ray,

I am just trying to mimic uvm_components_param_utils type behavior.

**Comment by raysalemi** [comment]
**pyuvm** does not use the `uvm_component_utils` or `uvm_object_utils`
macros.

There is no need for them in Python.
