### ISSUE TITLE
Add UVM Register Access Sequences

### ISSUE THREAD

**Issue by eminakgun** [pyuvm/pyuvm#197]
Hi, I was looking for RAL access sequences that exists in UVM standard. Are there any ongoing work that I've missed?

**Comment by raysalemi** [comment]
Hi!

RAL is at the HEAD of master right now.  I will be releasing a `dev` version next week.

**Comment by eminakgun** [comment]
See [discussion](https://github.com/pyuvm/pyuvm/discussions/161#discussioncomment-9815604)
