### ISSUE TITLE
Multiple analysis (imp)ports in a scoreboard

### ISSUE THREAD

**Issue by marcorogo13** [pyuvm/pyuvm#202]
Hi all, I would like to know if it is possibile to implement the equivalent of the following SV code in pyuvm, having a monitor  (dut) and a ref model that need to write to the scoreboard for comparison. 
```
`uvm_analysis_imp_decl(_DUT)
`uvm_analysis_imp_decl(_MODEL)

class cve2_core_scoreboard extends uvm_scoreboard;

  `uvm_component_utils(cve2_core_scoreboard) 
  
  uvm_analysis_imp_DUT #(cve2_core_seq_item, cve2_core_scoreboard) from_dut;
  uvm_analysis_imp_MODEL #(cve2_core_seq_item, cve2_core_scoreboard) from_model; 
...
  function void cve2_core_scoreboard::write_DUT(input cve2_core_seq_item t);
    seq_qu_dut.push_back(t);
  endfunction
  
  function void cve2_core_scoreboard::write_MODEL(input cve2_core_seq_item t);
    seq_qu_model.push_back(t);
  endfunction
```

How would it be possible to differentiate the two write methods in pyuvm? Thanks in advance!

**Comment by raysalemi** [comment]
You can create code that looks like this when it connects:

```Python
        self.cmd_mon.ap.connect(self.scoreboard.cmd_export)
        self.result_mon.ap.connect(self.scoreboard.result_export)
```

You can see the example in the Python for RTL Verification examples: https://github.com/raysalemi/Python4RTLVerification/tree/master/37_components_in_testbench_6.0

Ray

**Comment by marcorogo13** [comment]
Thanks a lot Ray! Yes I was thinking still in SV terms, having to implement the write of the import side. 
By the way great work on the port to python of UVM!

**Comment by raysalemi** [comment]
Thanks!
