### ISSUE TITLE
uvm_report_object init gets slow for generated tests

### ISSUE THREAD

**Issue by LeoGoTi** [pyuvm/pyuvm#214]
Hi, I have a performance-related problem on `uvm_report_object`.

It's about the initialization, the logger name, and the `setLevel` call.

## Steps to reproduce
It's simple. I use a while loop to `@pyuvm.test()`'d a test class multiple times.
The test have relatively stable behavior. I mean in the profiling `.svg` outputs, they share the similar number of calls on methods.

The problem is, the simulation speed gets slower per test. See this screenshot.
<img width="665" alt="image" src="https://github.com/pyuvm/pyuvm/assets/34080900/6e63b72f-bab8-4146-aafc-4731552aeaa9">

When test id is `02`, the `setLevel()` costs:
<img width="152" alt="image" src="https://github.com/pyuvm/pyuvm/assets/34080900/29854629-22ec-4c89-8a3b-4de4c95a8db0">

While test id grows to `39`, the `setLevel()` costs:
<img width="186" alt="image" src="https://github.com/pyuvm/pyuvm/assets/34080900/01978a51-8e9c-4047-be49-7b8da143b9bd">

## Locate the hotspot
I found that the slow-down comes from the `setLevel` call on the object's logger.
```python
class uvm_report_object(uvm_object):
    __default_logging_level = logging.INFO
    """ The basis of all classes that can report """
    def __init__(self, name):
        super().__init__(name)
        uvm_root_logger = logging.getLogger('uvm')
        # Every object gets its own logger
        logger_name = self.get_full_name() + str(id(self))
        self.logger = uvm_root_logger.getChild(logger_name)
        self.logger.setLevel(
            level=uvm_report_object.get_default_logging_level())
```

I have tried to remove the `setLevel` call, and another way to make the `logger_name` to `self.get_full_name()`, without the id-string suffix.

Only the latter helps to restore to my expected speed, but causing the output format strange (with multiple duplicates of  the `get_full_name()` string wrapped in brackets).

## My question
I am curious about the reason for making the logger name one with id-string suffix.
- What is the actual need for per-instance logger instead of per-`get_full_name()` logger?
- What is the root cause of the strange duplicate string when I have removed the id-string suffix?
- Is there a way to workaround or to fix?

**Comment by raysalemi** [comment]
I don't understand what you're saying here:

>Only the latter helps to restore to my expected speed, but causing the output format strange (with multiple duplicates of the get_full_name() string wrapped in brackets).

What is "the latter" in this sentence?  Do you mean you see normal performance if you don't call `str(id(self)`?

Given that I don't understand that part, here are my current answers:

* We need the per-instance logger so we can implement the hierarchical reporting control in the UVM
* I'm not sure what you mean by the "duplicate string".  Is your loop giving all the tests the same name? That would explain it, right?
* I don't understand the problem yet, so I can't answer this one.

**Comment by raysalemi** [comment]
Looking over the **logging** source code, I see that setLevel cannot be the problem:

```Python
    def setLevel(self, level):
        """
        Set the logging level of this handler.  level must be an int or a str.
        """
        self.level = _checkLevel(level)
```

`_checkLevel` simply converts a string to the appropriate integer. It's short and simple.

**Comment by raysalemi** [comment]
Are you sure this is the hotspot?

If it is, what happens if you replace `str(id(self))` with a random number from the **random** package?

**Comment by LeoGoTi** [comment]
Sorry for the confusion I made. I'll try to make it more clear.

### logger_name
> Do you mean you see normal performance if you don't call str(id(self)?

Yes, the performance remains stable (around `10000ns/s`) for all generated cases, if I assign only `self.get_full_name()` to `logger_name`.

### Duplicate string
> I'm not sure what you mean by the "duplicate string".

The string looks like:
```
28005.02ns INFO     ..tb/pte/pte_scoreboard.py(337) [uvm_test_top.pte_env.scb]: [uvm_test_top.pte_env.scb]: [uvm_test_top.pte_env.scb]: [uvm_test_top.pte_env.scb]: [uvm_test_top.pte_env.scb]: [uvm_test_top.pte_env.scb]: [uvm_test_top.pte_env.scb]: [uvm_test_top.pte_env.scb]: [uvm_test_top.pte_env.scb]: [uvm_test_top.pte_env.scb]: [uvm_test_top.pte_env.scb]: [uvm_test_top.pte_env.scb]: [uvm_test_top.pte_env.scb]: [uvm_test_top.pte_env.scb]: [uvm_test_top.pte_env.scb]: [uvm_test_top.pte_env.scb]: [uvm_test_top.pte_env.scb]: A set of check passed
```

### The generation loop
> Is your loop giving all the tests the same name? That would explain it, right?

I should firstly explain that, since I want to make tests comparable to each other, I used the loop on the completely same test class. The actual tests are different, but shows similar performance degradation.

To make it even more straight, let me put the loop code here.
```python
for comb in param_combs:
    gen_test = type(
        f"Gen{self._test_id}", (cls,),
        {"__doc__": cls.__doc__ + f"\nTest parameters: {comb}", "test_params": comb})
    pyuvm.test(**pyuvm_test_args)(gen_test)
    _test_id += 1
```
- The `param_combs` are the combinations of parameters that I want to pass to tests. Here it contains same elements.
- I create the subclass using `type()`, updating the name and docstring. But yes, the base class are the same.

### The `setLevel` method
I use `python-3.12`, the `setLevel` seems different:
```python3
def setLevel(self, level):
    """
    Set the logging level of this logger.  level must be an int or a str.
    """
    self.level = _checkLevel(level)
    self.manager._clear_cache()
```
The hotspot is actually the `_clear_cache` call.
<img width="710" alt="image" src="https://github.com/pyuvm/pyuvm/assets/34080900/4b49fa7c-3eb1-48d2-b14e-dbac98261978">

**Comment by raysalemi** [comment]
I can't speak to the `_clear_cache` method. I suspect it is getting a very long name and using it as a key to a dict.

I am trying to understand what happens when you use the `pyuvm.test()` decorator this way as it is the thing printing that long string.

**Comment by LeoGoTi** [comment]
The problem may originate from the `add_logging_handler` call in `uvm_report_object.__init__()`.
- Removing `+ str(id(self))` makes my scoreboard using the same logger, across multiple `@pyuvm.test()`'d tests in one test module.
- `add_logging_handler` lets the handler list in the logger grow. i.e., at the 40-th test, it will have 40 handlers in the list.
- The `format()` method in `PyuvmFormatter` will modify the record instance, concatenating the msg string and render it a longer string.


I wonder if the `+ str(id(self))` is really necessary. In pyuvm, the full-path's are unique among all uvm_report_object, I assume?

 If so maybe the code should ensure that only one handler is added into the logger's handlers list. (I am not sure about Python's GC mechanism. If `id()` may be reused, the list is also prone to have duplicate handlers appended during different tests.)

And if not, maybe we should consider making the logger dict as simple as possible, so as to reduce the `setLevel --> _clear_cache` cost.

**Comment by raysalemi** [comment]
The goal of `str(id(self))` was specifically not to have the same handler across multiple tests, or across multiple components.

All tests get called `uvm_test_top`, so one can't us the full name to distinguish them.

You can manually change the handler in your tests by calling `remove_logging_handler` and `add_logging_handler` with the handler you want.

**Comment by raysalemi** [comment]
I have a better solution...

**Comment by raysalemi** [comment]
If you pull the latest from pyuvm, you can create a base test that overrides `get_intial_logger_name` with whatever algorithm you want to use to create an initial logger name.

I still need to add some tests for this.

**Comment by raysalemi** [comment]
Please let me know if this solves your issue.

**Comment by LeoGoTi** [comment]
Thanks! This update should let my tests run at better speed with tiny amendment on current code.

As I understand it, It should be like:
```python
# define get_initial_logger_name()
def get_initial_logger_name:
    return self.get_full_name()

# Init stage
super().__init__()
if len(self.logger.handlers) == 2: # On the second decorated test, the second handler has been appended.
    self.remove_streaming_handler() # This will remove the newly-appended handler
```

The combination of the above amendments worked well for me. Please feel free to close the issue.

Thanks again. 😁

**Comment by raysalemi** [comment]
I'm glad we could solve this. Your innovation of using Python to create multiple tests is cool, and I'm glad **pyuvm** can support it so easily.
