### ISSUE TITLE
Use `pytest` as a testing framework

### ISSUE THREAD

**Issue by tudortimi** [pyuvm/pyuvm#8]
`pytest` can be used for both unit testing, but also for end-to-end testing (when testing with a simulator). It leads to more readable test code.

**Comment by tudortimi** [comment]
Do you have any strong preference for `nose` and `unittest`? `pytest` is by far the more popular framework.

**Comment by tudortimi** [comment]
I could try to convert the existing unit tests to `pytest` to give you a glimpse.

**Comment by tudortimi** [comment]
The cool thing is that `pytest` supports "classical" `unittest` tests as well, so it's not an "all or nothing" proposition. Test code can be migrated incrementally, if needed.

**Comment by tudortimi** [comment]
> Does `pytest` affect running the **cocotb** testbenches using `tox` to call `make`?

Can't say for sure, but I would assume everything would still work. The unit tests (in the `nosetests` directory) are anyway separate from the cocotb tests.

**Comment by raysalemi** [comment]
I've merged in your PR.  Thank you!
