### ISSUE TITLE
Nested raise/drop objections do not work as expected

### ISSUE THREAD

**Issue by lucacog** [pyuvm/pyuvm#87]
Hi,

From what I see raise_objection/drop_objection logic does not work as expected in case of nested objections.
assuming the following pseudo code:
```
 class test_a(uvm_tests):
     async def run_phase(self):
          self.raise_objection()
          await self.something_to_do()
          self.drop_objection()
```
```
 class test_b(test_a):
      async def run_phase(self):
           self.raise_objection()
           await super().run_phase()
           await self.something_else_to_do()
           self.drop_objection()
```
while executing test_b, the method self.something_else_to_do() will not be executed because the objection raised by test_b is cleared by the drop_objection of test_a

From what I see in the utility_classes code, this happens because in the class ObjectionHandler the attribute self.objection_raised is a boolean instead of a counter

Cheers,
Luca

**Comment by raysalemi** [comment]
If raise_objection() is called twice it should not exit the run phase until drop_objection has been called twice.  Are you not seeing this?

**Comment by raysalemi** [comment]
I've looked into it.  The run phase only ends if the `self.__objections` is empty.  So in the example above, the first call to `drop_objection()` would not empty the list.  Am I missing something?

```python
    def raise_objection(self, raiser):
        self.__objections[raiser] = raiser.get_full_name()
        self.objection_raised = True
        self._objection_event.clear()

    def drop_objection(self, dropper):
        try:
            del self.__objections[dropper]
        except KeyError:
            self.objection_raised = True
            pass
        if len(self.__objections) == 0:
            self._objection_event.set()
```

**Comment by lucacog** [comment]
> If `raise_objection()` is called twice the test should not exit the run phase until `drop_objection()` has been called twice. Are you not seeing this?

exactly, I am not seeing this. But I am not seeing it only when is the same instance is calling the raise_objection() twice (one inside the super().run_phase())

the drop objection() deletes self.__objections[dropper] without checking how many raise_objections() have been called for that instance. If this is not completely clear I can try to make a small scenario that triggers is

**Comment by raysalemi** [comment]
Oh, I why that is happening.  The code stores the instance in a dictionary using the instance handle as the key.  So there is only one entry for that instance and thus the first `drop_objection` removes it and leaves the run phase.

Definitely a bug.  Good catch!

**Comment by raysalemi** [comment]
I  never wrote a test for this scenario as it never occurred to me.

**Comment by lucacog** [comment]
In SV I often use test class inheritance, where I wrap the parent run_phase with an objection, in a similar way to what I wrote in  the example earlier. So I encountered this issue pretty fast, but I could not understand until today what was causing my test to end prematurely.
For the rest I am really happy with pyuvm, I am still learning how to use it, but after more than a decade of systemverilog uvm, I find pyuvm really refreshing and a step in the right direction

**Comment by raysalemi** [comment]
> In SV I often use test class inheritance, where I wrap the parent run_phase with an objection, in a similar way to what I wrote in the example earlier. So I encountered this issue pretty fast, but I could not understand until today what was causing my test to end prematurely.
> For the rest I am really happy with pyuvm, I am still learning how to use it, but after more than a decade of systemverilog uvm, I find pyuvm really refreshing and a step in the right direction

Thanks!  I'll have a fix in by this week.

**Comment by raysalemi** [comment]
I've fixed it while waiting for soup to cook. :)

```python

    def raise_objection(self, raiser):
        name = raiser.get_full_name()
        self.__objections[name] = self.__objections.setdefault(name, 0) + 1    # count up
        self.objection_raised = True
        self._objection_event.clear()

    def drop_objection(self, dropper):
        name = dropper.get_full_name()
        try:
            self.__objections[name] -= 1    # count down
        except KeyError:
            self.objection_raised = True
            pass
        if self.__objections[name] == 0:
            del self.__objections[name]
            self._objection_event.set()
```
