### ISSUE TITLE
Simplify making tests

### ISSUE THREAD

**Issue by ktbarrett** [pyuvm/pyuvm#89]
From the example I see the following code repeated often.

```python
@cocotb.test()
async def alu_test(_):
    """Test ALU with random and max values"""
    await uvm_root().run_test(AluTest)
```

It seems like you need to manually write this stub for every test. This could perhaps be simplified by adding a metaclass to `uvm_test` to instrument tests so they behave as coroutines and can be directly decorated with `@cocotb.test()` or use in `TestFactory`. In the end it would look like the following.

```python
@cocotb.test(timeout=1, timeout_unit='ns')
class AluTest(uvm_test):
    ...
```

**Comment by raysalemi** [comment]
I'd be open to a PR that did this.  I'm not sure how to add multiple metaclasses to a class, as `uvm_test` extends `uvm_void` which has a metaclass to implement the factory.

**Comment by raysalemi** [comment]
I'm currently knee deep in adding "Figure" comments to all the code fragments in the book. My wife had a great idea to put 

```
# Figure N: 
```

Into the code fragments so they'd be in both the epub and paper versions of the book.

**Comment by raysalemi** [comment]
If you'd could implement the PR, I would do the work to fix the tests and what-not and modify the book to reflect the new approach.

**Comment by ktbarrett** [comment]
I'll open a PR this evening or tomorrow.

**Comment by ktbarrett** [comment]
> What do you mean by a "base uvm_test class"? Do you mean that one could not define a test that extends another test, that seems counter to "it would allow inheriting from any test"

I mean that all classes that subclass directly or indirectly from uvm_test are implicitly cocotb tests that will be run, you cannot create a partial test.

```python
class MyTestBase(uvm_test):
    """Base class for actual tests, don't want this to actually run"""

class MyTest1(MyTestBase):
     ...

class MyTest2(MyTestBase):
     ...
```

Another issue with the metaclass approach is that you can't parameterize the `cocotb.test(...)` function call.

However there is a hidden third option...

## Specialized Decorator

Instead of applying `@cocotb.test()` to `uvm_test` classes, we can instead create a `@pyuvm.test()` decorator that creates a `cocotb.test` object, adds it to the caller's global scope, and returns the test class unmolested, allowing for further subclassing. That would look something like the following.

```python
class AluTestBase(uvm_test):
    """Not actually run"""

@pyuvm.test()
class AluTest(AluTestBase):
    ...

@pyuvm.test()
class ParallelAluTest(AluTest):
    ...
```

This would avoid all problems with the other approaches. You can parameterize the test decorator, like you could `@cocotb.test()`; and you can further subclass decorated subclasses.
