### ISSUE TITLE
Uvm_sequence get_response() does not return the correct response to a request

### ISSUE THREAD

**Issue by miserva** [pyuvm/pyuvm#98]
get_response() in uvm_sequence does not actually return the response to a request - it only returns the next response item in the queue whether or not it is the response to that specific request transaction. This works by chance as long as responses come in the same order as requests, but if you leave out get_response() from one of your own sequences, you can see requests and responses get all messed up.

The reason for this is that uvm_sequence get response() is passing running_item's (request's) response_id, which is always None, so it defaults to returning the next response item in the queue. Changing it to passing running_item's transaction_id instead should be the fix for this, but I can only verify this in my own testbench since pyuvm's sequence test is broken at least for me.

**Comment by raysalemi** [comment]
Does your code call `set_id_info()` like this?

            result_item = AluResultItem("result_item", result)
            result_item.set_id_info(cmd)
            self.seq_item_port.item_done(result_item)

**Comment by miserva** [comment]
Yes. I have do_copy() implemented in my sequence item, and in my driver I have:
```python
resp = req.clone()
resp.set_id_info(req)
# drive transaction
self.seq_item_port.item_done()
self.seq_item_port.put_response(resp)
```
And here is how my sequence body looks like in general for good measure:
```python
async def body(self):
    tr = seq_item.create("seq_item_tr")
    resp = seq_item.create("seq_item_resp")
    await self.start_item(tr)
    # prepare tr
    await self.finish_item(tr)       
    resp = await self.get_response()
```
Let me demonstrate what happens when I leave out get_response() from my write sequence to clog up the response queue, and do a write and then read. I have 55555555 stored in a memory address, so I am expecting to get that back from the read.
```
#   1500.00ns DEBUG    driver.py(37)[uvm_test_top.env.agent.driver]: req tr_id: 2aaabfee5e10
#   1500.00ns DEBUG    driver.py(40)[uvm_test_top.env.agent.driver]: resp tr_id: 2aaabfee5e10
#   1500.00ns INFO     driver.py(54)[uvm_test_top.env.agent.driver]: write access, addr: 1004, data: 0
#   1800.00ns DEBUG    driver.py(37)[uvm_test_top.env.agent.driver]: req tr_id: 2aaabff01910
#   1800.00ns DEBUG    driver.py(40)[uvm_test_top.env.agent.driver]: resp tr_id: 2aaabff01910
#   1800.00ns INFO     driver.py(62)[uvm_test_top.env.agent.driver]: read access, addr: 1000
#   1800.00ns INFO     monitor.py(67)[uvm_test_top.env.agent.monitor]: write: addr: 1004, data: 0
#   2100.00ns INFO     monitor.py(45)[uvm_test_top.env.agent.monitor]: read: addr: 1000, data: 55555555
#   2200.00ns INFO     uvm_sequence.get_response: self.running_item.response_id = None
#   2200.00ns DEBUG    read_seq.py(37)[]: read sequence resp tr_id: 2aaabfee5e10
#   2200.00ns ERROR    read_seq.py(62)[]: 1000 data not expected: exp:55555555 act:0
#   2200.00ns INFO     test_all_seq.py(15)[]: Response queue contents: ['seq_item_tr: addr:1000, data:55555555, OP:READ(0)']
```
The sequencer handed out the write response to my read sequence. This is because uvm_sequence.get_response() passed None to sequencer.get_response() so the sequencer just gave the first item in the queue.
Now let me show what happens when uvm_sequence.get_response() passes running_item.transaction_id instead.
```
#   1500.00ns DEBUG    driver.py(37)[uvm_test_top.env.agent.driver]: req tr_id: 2aaabfefbd90
#   1500.00ns DEBUG    driver.py(40)[uvm_test_top.env.agent.driver]: resp tr_id: 2aaabfefbd90
#   1500.00ns INFO     driver.py(54)[uvm_test_top.env.agent.driver]: write access, addr: 1004, data: 0
#   1800.00ns DEBUG    driver.py(37)[uvm_test_top.env.agent.driver]: req tr_id: 2aaabbdab950
#   1800.00ns DEBUG    driver.py(40)[uvm_test_top.env.agent.driver]: resp tr_id: 2aaabbdab950
#   1800.00ns INFO     driver.py(62)[uvm_test_top.env.agent.driver]: read access, addr: 1000
#   1800.00ns INFO     monitor.py(67)[uvm_test_top.env.agent.monitor]: write: addr: 1004, data: 0
#   2100.00ns INFO     monitor.py(45)[uvm_test_top.env.agent.monitor]: read: addr: 1000, data: 55555555
#   2200.00ns INFO     uvm_sequence.get_response: self.running_item.transaction_id = 2aaabbdab950
#   2200.00ns DEBUG    read_seq.py(37)[]: read sequence resp tr_id: 2aaabbdab950
#   2200.00ns INFO     read_seq.py(64)[]: 1000 data as expected: 55555555
#   2200.00ns INFO     test_all_seq.py(15)[]: Response queue contents: ['seq_item_tr: addr:1004, data:0, OP:WRITE(1)']
```
The read sequence was passed the correct response, and the write response is left hanging in the queue as expected.

**Comment by raysalemi** [comment]
Good catch!  There is definitely a bug here as I made a mistake refactoring the sequences.  Here is the definition of `uvm_sequence.get_response()`.  I'd like to make sure you read it the way I do.

```
virtual task get_response(
   	output 	RSP 	response,	  	
   	input 	int 	transaction_id	 = 	-1
)
By default, sequences must retrieve responses by calling get_response.  If no transaction_id is specified, this task will return the next response sent to this sequence.  If no response is available in the response queue, the method will block until a response is received.

If a transaction_id parameter is specified, the task will block until a response with that transaction_id is received in the response queue.

The default size of the response queue is 8.  The get_response method must be called soon enough to avoid an overflow of the response queue to prevent responses from being dropped.

If a response is dropped in the response queue, an error will be reported unless the error reporting is disabled via set_response_queue_error_report_disabled.
```

What does your working code look like?   Do you pass `self.running_item.transaction_id`?

Ray

**Comment by raysalemi** [comment]
There was a lot about the sequence specification that I couldn't figure out. But I knew how it was supposed to work, so I rewrote it. This is the last wrinkle. I'll make the change and fix the test.

**Comment by raysalemi** [comment]
Would you like to try the pull request and see if it solves the problem?

**Comment by miserva** [comment]
Yes, the pull request passes my test.

**Comment by raysalemi** [comment]
> Yes, the pull request passes my test.

Merged. 

Thanks!
